export enum Category {
  Arhitektura = 1,
  Bastina = 2,
  CivilnoDrustvo = 3,
  Dizajn = 4,
  Edukacija = 5,
  Film = 6,
  Knjiga = 7,
  KulturnaPolitika = 8,
  Mediji = 9,
  Muzika = 10,
  Nauka = 11,
  Pozoriste = 12,
  Strip = 13,
  Tehnologija = 14,
  VizuelnaUmetnost = 15,
}
